### ISSUE TITLE
alignment score of LARA2

### ISSUE THREAD

**Issue by kad-ecoli** [seqan/lara#1]
I am using LARA2 for pairwise alignment. In the default T-COFFEE output, there is alignment score for each aligned residue pairs. However, there is no total score of aligning the full sequence (which should include the gap penalties). Is there somewhere I can get this piece of information?

**Comment by joergi-w** [comment]
Hi, thank you for using my tool and providing feedback!

The total score of aligning two sequences exists in the program code, but the [T-Coffee format](http://www.tcoffee.org/Projects/tcoffee/documentation/index.html#t-coffee-lib-format-01) does not support the output of these alignment scores. As it would be simple to implement this output, I can offer to add this to LaRA2's capabilities within a week or so. 

In which format would you like to retrieve the scores (e.g. csv file `seqA,seqB,5`)? Should the scores contain only sequence alignment with gap penalty, or also the structure contribution?

**Comment by kad-ecoli** [comment]
Yes, a csv format with ``seqA,seqB,S`` will be great if ``seqA`` and ``seqB`` are the (gapped) alignment. Since the LARA alignment comes from both sequence and structure, it will make sense to include both in the output score.

**Comment by joergi-w** [comment]
I have a better idea, if you want the gapped alignment together with the score (I had in mind to write only the sequence identifiers into the csv). There exists already the output option `-o pairs`, which prints the pairwise alignments. I can simply add the score to the header line of each pair pairwise alignment as shown in the following example.

```console
>seq1 && seq2 (score 17)
ACCGUUG
ACC-UGG
```

**Comment by kad-ecoli** [comment]
That should also work.

**Comment by joergi-w** [comment]
I made new commits to the `master` branch implementing the output of the score as noted above.
Feel free to check out the new version!

**Comment by kad-ecoli** [comment]
Yes, the -pairs option gives the score. Thank you.

**Comment by kad-ecoli** [comment]
I closed this issue too early. Something is wrong with the output score. For the same RNA pair, depending on the input order, the output score from -pair is vastly different.

```
$ ../build/lara -i input.fasta -o pairs
>7mqaL2 && 6az33 (score 57.6367)
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCU-CCGUA---UUGGGGAG--UGAGAGGGAGAGAACGCGGUCUGAGUGGU
---AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGG--GCUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGU-GU
$ ../build/lara -i seq.fasta -o pairs
>6az33 && 7mqaL2 (score 72.4994)
---AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGGG--CUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGUG-U
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGC-GUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUU--GGGGAG---UGAGAGGGAGAGAACGCGGUCUGAGUGGU
$ cat seq.fasta 
>6az33
AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGGGCUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGUGU
>7mqaL2
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUUGGGGAGUGAGAGGGAGAGAACGCGGUCUGAGUGGU
$ cat input.fasta 
>7mqaL2
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUUGGGGAGUGAGAGGGAGAGAACGCGGUCUGAGUGGU
>6az33
AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGGGCUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGUGU
```

**Comment by joergi-w** [comment]
You spotted a mistake – thank you!
When the algorithm chooses the maximum profitable edge, it only considered the first element in the priority queue. But sometimes there are two or more leading elements with maximal score. I provide a fix in the master branch that considers all maximum scoring edges. With this version the score is the same even if you swap the input sequences, and I also find that the results are improved.

**Comment by kad-ecoli** [comment]
The results are indeed slightly improved if the aligned RNAs are not too different.
